version: '3.8'

services:
  blue:
    image: 839983937363.dkr.ecr.ap-northeast-2.amazonaws.com/forday:latest
    container_name: blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - ENV=blue
    restart: always
